version: '3'

services:
  db:
    image: mysql:latest
    command: mysqld --default-authentication-plugin=mysql_native_password
    volumes:
      - "./mysql:/var/lib/mysql"
    restart: always
    environment:
       MYSQL_DATABASE: 'request_processor'
       MYSQL_USER: 'dj_admin'
       MYSQL_PASSWORD: 'django'
       MYSQL_ROOT_PASSWORD: 'django'
  web:
    restart: always
    build: .
    command: "python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/RequestProcessor
    ports:
      - "8000:8000"
    depends_on:
      - db
