# Generated by Django 3.0.8 on 2020-07-10 09:17

from django.db import migrations, models
import django.db.models.deletion

from RequestProcessor.models import Customer


def insertdata(apps, schema_editor):
    Customer(name = 'Big News Media Corp').save()

    Customer(name = 'Online Mega Store').save()

    Customer(name = 'Nachoroo Delivery', active=False).save()

    Customer(name='Euro Telecom Group').save()


class Migration(migrations.Migration):

    dependencies = [
        ('RequestProcessor', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(insertdata),
    ]
