# Generated by Django 3.0.8 on 2020-07-10 09:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    atomic = True
    dependencies = [
        ('RequestProcessor', '0002_insertdata'),
    ]

    operations = [
        migrations.CreateModel(
            name='HourlyStats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('hour', models.IntegerField()),
                ('request_count', models.BigIntegerField(default=0)),
                ('invalid_count', models.BigIntegerField(default=0)),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='RequestProcessor.Customer')),
            ],
            options={
                'unique_together': {('customer', 'date', 'hour')},
            },
        ),
    ]
